# Generated by Django 4.1.4 on 2023-01-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Confirmed', 'confirmed'), ('Rejected', 'rejected')], default='Pending', max_length=20),
        ),
    ]
