# Generated by Django 4.1.4 on 2023-01-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_appointment_confirmed_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
